name: Deploy on comment
on:
  issue_comment:
    types: created
jobs:
  deploy:
    name: Deploy
    if: github.event.comment.body == '/deploy'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        env:
          AUTOUPDATE_URL: http://IP/update
          AUTOUPDATE_AUTH: ${{ secrets.AUTOUPDATE_AUTH }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          repository="$(jq -er .repository.full_name "${GITHUB_EVENT_PATH}")"
          pull_request="$(jq -er .issue.number "${GITHUB_EVENT_PATH}")"
          auth_header="Authorization: Token ${GITHUB_TOKEN}"
          github_api="https://api.github.com/repos/${repository}"
          branch_name="$(curl -sSL -H "${auth_header}" "${github_api}/pulls/${pull_request}" | jq -er .head.ref)"
          tag="$(echo "${branch_name}" | sed 's/[^a-zA-Z0-9_.-]/-/g')"
          curl -sS -u "${AUTOUPDATE_AUTH}" "${AUTOUPDATE_URL}?image=myapp&tag=${tag}"
